edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
reorder_modules = true
# The following are nightly-only. Enable them when we move to nightly rustfmt:
# group_imports = "StdExternalCrate"
# imports_granularity = "Module"
