// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Lightweight probe the frontend calls on mount to confirm the bridge is live.
 */
async healthCheck() : Promise<HealthStatus> {
    return await TAURI_INVOKE("health_check");
},
/**
 * Start a streaming transcription session. Events are pushed through
 * the supplied `Channel<TranscriptEvent>` until [`stop_streaming`] is
 * invoked or the capture stream ends. Persists to SQLite incrementally
 * via the [`MeetingRecorder`].
 */
async startStreaming(options: StartStreamingOptions | null, onEvent: TAURI_CHANNEL<TranscriptEvent>) : Promise<Result<StreamingSessionId, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_streaming", { options, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop a previously-started streaming session. Idempotent: returns
 * `Ok(false)` when the session id is unknown (already stopped or
 * never existed).
 */
async stopStreaming(sessionId: StreamingSessionId) : Promise<Result<boolean, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_streaming", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List meetings, newest first.
 */
async listMeetings(limit: number | null) : Promise<Result<MeetingSummary[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meetings", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch a single meeting (header + segments). Returns `null` when
 * the id does not exist.
 */
async getMeeting(id: MeetingId) : Promise<Result<Meeting | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a meeting and its segments. Returns `true` when the row
 * existed and was removed.
 */
async deleteMeeting(id: MeetingId) : Promise<Result<boolean, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a diarized speaker (or clear the label back to anonymous
 * by passing `null`/empty). Returns the freshly-loaded meeting so
 * the frontend can re-render speakers + segment chips from a single
 * source of truth without an extra `get_meeting` round-trip.
 */
async renameSpeaker(meetingId: MeetingId, speakerId: SpeakerId, label: string | null) : Promise<Result<Meeting, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_speaker", { meetingId, speakerId, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full-text search over segment text. Returns one hit per meeting,
 * ordered by FTS5 BM25 rank (best match first). Empty / whitespace-
 * only queries return an empty vec — the frontend wires this to
 * `onChange` debounced, so the initial empty state never errors.
 * 
 * `limit` defaults to 20 (a comfortable sidebar page); `0` means no
 * cap. The query is sanitised inside the storage layer, so the
 * frontend can pass raw user input without worrying about FTS5
 * syntax characters.
 */
async searchMeetings(query: string, limit: number | null) : Promise<Result<MeetingSearchHit[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_meetings", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate (or regenerate) the local-LLM summary for a meeting.
 * 
 * `template` selects the prompt template: `"general"` (default),
 * `"oneOnOne"`, `"sprintReview"`, `"interview"`, `"salesCall"`, or
 * `"lecture"`. Passing `null` or omitting the field defaults to
 * `"general"`.
 */
async summarizeMeeting(meetingId: MeetingId, template: string | null) : Promise<Result<Summary, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_meeting", { meetingId, template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the most recent summary for a meeting, or `null` when none
 * has been generated yet. The frontend uses this on `MeetingDetail`
 * mount so the panel can render either the existing summary or the
 * "Generate" affordance without a redundant generate call.
 */
async getSummary(meetingId: MeetingId) : Promise<Result<Summary | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_summary", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run one chat turn against a meeting's transcript.
 * 
 * Each invocation streams the assistant's reply token-by-token through
 * `on_event` and resolves the IPC promise once the stream terminates
 * (with [`AskAboutMeetingEvent::Finished`] on success or
 * [`AskAboutMeetingEvent::Failed`] on a mid-decode error).
 * 
 * ## Lifecycle
 * 
 * 1. Pre-stream errors (meeting not found, empty question, model
 * not loaded) come back as `Err(String)` so the UI can show a
 * toast without parsing event variants.
 * 2. Once the stream is open, **every** terminal condition travels
 * as a final event on the channel: success → `Finished`,
 * mid-decode failure → `Failed`. The promise then resolves
 * `Ok(())`.
 * 3. Cancellation is automatic: when the React component unmounts
 * (or the user closes the chat panel), Tauri drops the
 * `Channel`. The next `on_event.send` returns `Err(_)`, this
 * function exits its drain loop, the `BoxStream` is dropped, the
 * underlying `mpsc::Receiver` closes and the blocking decoder
 * thread inside `LlamaCppChat` exits on the next
 * `tx.blocking_send` failure. No explicit `cancel_chat` command
 * is needed — symmetric with `start_streaming` was deliberately
 * not chosen because chat is bounded (one Q&A turn ≤ ~10s on
 * Qwen 14B, vs streaming sessions that can run hours).
 * 
 * ## Why we don't spawn a background task
 * 
 * Unlike `start_streaming`, which returns a session id and runs
 * indefinitely until `stop_streaming`, a chat turn is a single
 * bounded interaction. Draining the stream inline keeps the IPC
 * surface minimal (one command, one channel, one promise) and means
 * any error gets observed by the calling `await` instead of escaping
 * into a detached `tokio::spawn`.
 */
async askAboutMeeting(meetingId: MeetingId, history: ChatMessage[] | null, question: string, onEvent: TAURI_CHANNEL<AskAboutMeetingEvent>) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ask_about_meeting", { meetingId, history, question, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a meeting (with optional summary) to a file at `dest_path`.
 * 
 * The frontend is responsible for showing the save-file dialog (via
 * `@tauri-apps/plugin-dialog`) and passing the chosen path here. This
 * command generates the formatted content and writes it atomically.
 */
async exportMeeting(meetingId: MeetingId, format: ExportFormat, destPath: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_meeting", { meetingId, format, destPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the status of all downloadable models.
 */
async getModelStatus() : Promise<ModelInfo[]> {
    return await TAURI_INVOKE("get_model_status");
},
/**
 * Download a model by id, streaming progress events to the frontend.
 */
async downloadModel(modelId: string, onEvent: TAURI_CHANNEL<DownloadEvent>) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * One actionable item extracted by the summarizer.
 * 
 * `owner` and `due` are best-effort; the LLM may leave either as
 * `None` when the transcript doesn't pin them down. The UI renders
 * them with sensible placeholders ("unassigned", "no due date") so
 * the summary remains useful even when partial.
 */
export type ActionItem = { 
/**
 * What needs to be done. Required — an action item without a
 * task is meaningless.
 */
task: string; 
/**
 * Who is on the hook. `None` when the transcript doesn't say.
 */
owner?: string | null; 
/**
 * Free-form deadline as the LLM extracted it ("Friday", "next
 * sprint", "2026-05-01"). Kept as a string on purpose — parsing
 * natural-language dates reliably is a separate problem and the
 * UI can render the raw text well enough for the MVP.
 */
due?: string | null }
/**
 * Events the use case streams back to the caller. The discriminator
 * is on `kind` (camelCase for the IPC wire format) so the React layer
 * can `switch (event.kind)` directly.
 * 
 * Variant order:
 * 
 * 1. Exactly one [`Started`](Self::Started) at the top of the
 * stream, carrying the model id for provenance.
 * 2. Zero or more [`Token`](Self::Token) deltas — one per logical
 * token the model produced.
 * 3. Exactly one terminator: either [`Finished`](Self::Finished)
 * with the assembled text and parsed citations, **or**
 * [`Failed`](Self::Failed) if the adapter raised an error
 * mid-stream.
 */
export type AskAboutMeetingEvent = 
/**
 * Stream is open; the model is about to start emitting tokens.
 * Carries the model id so the UI can show "powered by …" and so
 * chat-history persistence can stamp the right provenance.
 */
{ kind: "started"; model: string } | 
/**
 * One incremental piece of the model's reply. Forwarded verbatim
 * from [`echo_domain::ChatToken::delta`].
 */
{ kind: "token"; delta: string } | 
/**
 * Stream completed normally. Carries the full assembled reply and
 * the citations parsed from it (deduplicated, validated against
 * the meeting's real segment ids).
 */
{ kind: "finished"; text: string; citations: SegmentId[]; hadCitations: boolean } | 
/**
 * The adapter raised an error after the stream had already
 * started. The IPC layer SHOULD treat this as a final event and
 * stop polling.
 */
{ kind: "failed"; error: string }
/**
 * Sample-rate / channel configuration of a stream.
 * 
 * Wire format uses `camelCase` so the JSON that crosses the Tauri /
 * CLI boundary matches the TypeScript `AudioFormat` (`sampleRateHz`,
 * `channels`). SQLite persistence uses dedicated columns and does
 * not go through serde, so this rename is purely an IPC concern.
 */
export type AudioFormat = { 
/**
 * Sampling frequency in hertz.
 */
sampleRateHz: number; 
/**
 * Number of interleaved channels (1 = mono, 2 = stereo, ...).
 */
channels: number }
/**
 * A single message inside a [`ChatRequest`].
 * 
 * `content` is plain UTF-8 text — adapters that need a different chat
 * template format (Qwen's `<|im_start|>system\n…<|im_end|>`, Llama's
 * `[INST] … [/INST]`, …) wrap each `ChatMessage` accordingly. The
 * domain layer stays template-agnostic.
 */
export type ChatMessage = { 
/**
 * Who authored this message.
 */
role: ChatRole; 
/**
 * Plain-text content. Empty strings are tolerated (the use case
 * occasionally sends empty assistant messages to "prime" the
 * model into a specific format).
 */
content: string }
/**
 * Author of a single message in a chat exchange.
 * 
 * The three roles mirror the OpenAI / llama.cpp chat-template
 * vocabulary exactly so the adapter can fold them into `<|im_start|>`,
 * `<s>[INST]` or any other model-specific framing without translation
 * tables.
 */
export type ChatRole = 
/**
 * Top-of-conversation instructions — typically the transcript
 * excerpt and the "you are a helpful assistant…" preamble.
 * At most one per request, conventionally the first message.
 */
"system" | 
/**
 * A turn authored by the human user.
 */
"user" | 
/**
 * A turn authored by the model in a previous round of the same
 * conversation. Re-fed verbatim so the model can stay coherent
 * across turns.
 */
"assistant"
/**
 * A term/definition pair extracted from a lecture or class
 * (DEVELOPMENT_PLAN.md §3.2.6).
 */
export type Definition = { 
/**
 * The term being defined.
 */
term: string; 
/**
 * The definition provided.
 */
definition: string }
/**
 * Progress events streamed to the frontend during a download.
 */
export type DownloadEvent = 
/**
 * Periodic progress update.
 */
{ kind: "progress"; downloaded: number; total: number } | 
/**
 * Download finished successfully.
 */
{ kind: "finished" } | 
/**
 * Download failed.
 */
{ kind: "failed"; error: string }
/**
 * Machine-readable error codes the frontend can match on.
 * 
 * Kept intentionally coarse — add variants when the frontend needs
 * to distinguish a new failure mode, not for every conceivable
 * backend error.
 */
export type ErrorCode = 
/**
 * A required record (meeting, speaker, segment, …) was not found.
 */
"notFound" | 
/**
 * Persistent storage failed (SQLite I/O, migration, …).
 */
"storage" | 
/**
 * The local LLM could not load or inference failed.
 */
"llm" | 
/**
 * The ASR engine could not load or transcription failed.
 */
"asr" | 
/**
 * Input validation failed (empty question, bad template, …).
 */
"invalidInput" | 
/**
 * A streaming session conflict (poisoned map, duplicate id, …).
 */
"sessionConflict" | 
/**
 * A required model is not downloaded yet.
 */
"modelNotReady" | 
/**
 * Audio capture or device error.
 */
"audio" | 
/**
 * Voice activity detection failed.
 */
"vad" | 
/**
 * Speaker diarization failed.
 */
"diarization" | 
/**
 * An HTTP / network operation failed (model download, …).
 */
"network" | 
/**
 * Catch-all for unexpected / unclassified errors.
 */
"internal"
/**
 * Supported export formats.
 */
export type ExportFormat = "markdown" | "txt"
/**
 * Result returned by [`health_check`]. Mirrors `HealthStatus` on the TS side.
 */
export type HealthStatus = { 
/**
 * RFC 3339 timestamp of the probe.
 */
timestamp: string; 
/**
 * Backend semver, from Cargo at compile time.
 */
version: string; 
/**
 * Target triple the backend was compiled for.
 */
target: string; 
/**
 * Short git hash, `unknown` when `.git` is missing at build time.
 */
commit: string }
/**
 * A notable quote attributed to a speaker, used by the Interview
 * template (DEVELOPMENT_PLAN.md §3.2.4).
 */
export type InterviewQuote = { 
/**
 * Who said it.
 */
speaker: string; 
/**
 * Verbatim or near-verbatim quote.
 */
quote: string; 
/**
 * Situational context around the quote.
 */
context?: string | null }
/**
 * IPC mirror of [`echo_domain::AudioSource`] with camelCase naming
 * so the frontend stays stylistically consistent (the domain enum
 * uses snake_case for storage / CLI compatibility).
 */
export type IpcAudioSource = 
/**
 * Default microphone via cpal.
 */
"microphone" | 
/**
 * System audio loopback (macOS 13+ via ScreenCaptureKit).
 */
"systemOutput"
/**
 * Structured error returned by every Tauri command.
 * 
 * Serializes to `{ "code": "notFound", "message": "…", "retriable": false }`
 * on the IPC wire, which the frontend's `useIpcAction` hook can
 * destructure for precise UX.
 */
export type IpcError = { code: ErrorCode; message: string; retriable: boolean }
/**
 * Full meeting aggregate. Returned by point lookups and includes the
 * segment list and any diarized speakers.
 */
export type Meeting = 
/**
 * Summary projection.
 */
({ 
/**
 * Stable identifier.
 */
id: MeetingId; 
/**
 * Human-readable title. Defaults to `"Meeting <date>"` when the
 * caller does not supply one.
 */
title: string; 
/**
 * RFC 3339 instant the recording started.
 */
startedAt: string; 
/**
 * RFC 3339 instant the recording stopped. `None` while the
 * session is still running.
 */
endedAt: string | null; 
/**
 * Total audio captured, in milliseconds.
 */
durationMs: number; 
/**
 * Dominant language reported by the ASR backend (mode of
 * per-chunk languages). `None` until the first chunk lands.
 */
language: string | null; 
/**
 * Number of segments persisted.
 */
segmentCount: number }) & { 
/**
 * Audio format negotiated with the device.
 */
inputFormat: AudioFormat; 
/**
 * Decoded segments, ordered by `start_ms`. Each segment may
 * reference a `speaker_id` from `speakers`.
 */
segments: Segment[]; 
/**
 * Diarized speakers persisted for this meeting, ordered by
 * `slot`. Empty when no diarizer was wired into the pipeline.
 * `serde(default)` keeps older payloads (pre-Sprint 1 day 7)
 * loadable without speakers.
 */
speakers?: Speaker[] }
/**
 * Strongly-typed identifier for a [`Meeting`]. UUIDv7 keeps lexical
 * ordering aligned with creation time.
 */
export type MeetingId = string
/**
 * One hit returned by the search port. Carries the meeting summary
 * (so the sidebar can render it without an extra round-trip), the
 * FTS5 BM25 rank (smaller = better, by SQLite convention) and a
 * pre-rendered snippet around the strongest match. Snippet
 * boundaries are decided by SQLite's `snippet()` function and use
 * the markers chosen by the storage adapter — typically `<mark>` /
 * `</mark>` so the UI can render them as highlights.
 * 
 * `serde(rename_all = "camelCase")` keeps the wire format aligned
 * with the rest of the IPC surface.
 */
export type MeetingSearchHit = { 
/**
 * Meeting matched by the query.
 */
meeting: MeetingSummary; 
/**
 * Highlighted excerpt of the segment that matched.
 */
snippet: string; 
/**
 * FTS5 BM25 rank — *smaller is better* (negative numbers are
 * strongest matches). The UI should sort ascending; tests assert
 * the same. We keep the raw value rather than mapping to a
 * `[0,1]` score so consumers can decide their own normalisation.
 */
rank: number }
/**
 * Lightweight projection used by listing endpoints. Holds only what
 * the UI needs to render a row in the sidebar — *not* the segments.
 */
export type MeetingSummary = { 
/**
 * Stable identifier.
 */
id: MeetingId; 
/**
 * Human-readable title. Defaults to `"Meeting <date>"` when the
 * caller does not supply one.
 */
title: string; 
/**
 * RFC 3339 instant the recording started.
 */
startedAt: string; 
/**
 * RFC 3339 instant the recording stopped. `None` while the
 * session is still running.
 */
endedAt: string | null; 
/**
 * Total audio captured, in milliseconds.
 */
durationMs: number; 
/**
 * Dominant language reported by the ASR backend (mode of
 * per-chunk languages). `None` until the first chunk lands.
 */
language: string | null; 
/**
 * Number of segments persisted.
 */
segmentCount: number }
/**
 * A downloadable model known to the app.
 */
export type ModelInfo = { 
/**
 * Machine-readable id (e.g. `"asr-large-v3-turbo"`).
 */
id: string; 
/**
 * Human label shown in the UI.
 */
label: string; 
/**
 * Category: `"asr"`, `"llm"`, `"vad"`, or `"embedder"`.
 */
kind: string; 
/**
 * Whether the file exists on disk right now.
 */
present: boolean; 
/**
 * Approximate download size in bytes (for progress UI).
 */
sizeBytes: number }
/**
 * One contiguous transcription span.
 * 
 * `serde(rename_all = "camelCase")` keeps the wire format aligned
 * with the TypeScript `Segment` type in `src/types/segment.ts`, so
 * the `Meeting` aggregate returned by `get_meeting` exposes
 * `startMs` (not `start_ms`) — the same convention the streaming
 * `Chunk` event already uses for the segments it carries.
 */
export type Segment = { 
/**
 * Stable identifier.
 */
id: SegmentId; 
/**
 * Inclusive start offset, in milliseconds, relative to the
 * containing recording.
 */
startMs: number; 
/**
 * Exclusive end offset, in milliseconds. Always `>= start_ms`.
 */
endMs: number; 
/**
 * Decoded text. May be empty when the segment is silence or pure
 * non-speech but the ASR backend still emitted it.
 */
text: string; 
/**
 * Diarized speaker. `None` until diarization runs (Sprint 2).
 */
speakerId: SpeakerId | null; 
/**
 * Confidence in `[0.0, 1.0]`. `None` when the backend does not
 * report it (e.g. whisper.cpp without `temperature_inc`).
 */
confidence: number | null }
/**
 * Strongly-typed identifier for a [`Segment`]. UUIDv7 keeps lexical
 * ordering aligned with creation time, which simplifies SQLite
 * indexing later on.
 */
export type SegmentId = string
/**
 * One clustered voice within a meeting.
 * 
 * `slot` is the 0-based index of the speaker within the meeting,
 * assigned in arrival order. It drives the UI palette and the
 * default display name; it is **not** the database primary key
 * (that's [`SpeakerId`]).
 */
export type Speaker = { 
/**
 * Stable identifier.
 */
id: SpeakerId; 
/**
 * 0-based arrival order within the meeting. Drives the default
 * display name (`Speaker 1` for slot 0, etc.) and the color
 * palette index in the UI.
 */
slot: number; 
/**
 * User-assigned label, if any. `None` ⇒ render as
 * "Speaker {slot+1}". Limited to 80 characters at the storage
 * layer; the domain itself does not impose a length cap.
 */
label: string | null }
/**
 * Strongly-typed speaker identifier. UUIDv7 keeps insertion-time
 * ordering aligned with creation order.
 */
export type SpeakerId = string
/**
 * Options the frontend may pass when starting a streaming session.
 * All fields optional; defaults match `StreamingOptions::default()`.
 */
export type StartStreamingOptions = { 
/**
 * Capture source. `None` ⇒ microphone, preserving Sprint 0
 * behavior. `systemOutput` requires macOS 13+ with Screen
 * Recording permission (Sprint 1 day 2/3).
 */
source: IpcAudioSource | null; 
/**
 * ISO-639-1 language hint. `None` ⇒ auto-detect.
 */
language: string | null; 
/**
 * Capture device id. `None` ⇒ system default microphone. Ignored
 * when `source = systemOutput`.
 */
deviceId: string | null; 
/**
 * Audio chunk size in milliseconds. `None` ⇒ 5000.
 */
chunkMs: number | null; 
/**
 * RMS threshold below which a chunk is reported as `Skipped`
 * instead of being sent to the ASR. `None` ⇒ 0.02.
 */
silenceRmsThreshold: number | null; 
/**
 * Enable speaker diarization for this session. `None`/`false` ⇒
 * disabled (keeps Sprint 0 behaviour). When enabled the backend
 * loads the speaker embedder named by `ECHO_EMBED_MODEL` (or the
 * default path) and attaches an `OnlineDiarizer` to the pipeline,
 * so every emitted `Chunk` event carries `speakerId` +
 * `speakerSlot` and the meeting persists its speakers.
 */
diarize: boolean | null; 
/**
 * Override path to the speaker-embedder ONNX. `None` ⇒ use the
 * path resolved at app start. Mostly useful for tests / power
 * users; the UI does not surface it.
 */
embedModelPath: string | null; 
/**
 * Disable the neural (Silero) VAD for this session and fall back
 * to the energy-based RMS gate. `None`/`false` ⇒ neural VAD is
 * used when the ONNX model is installed (default and recommended:
 * fewer Whisper hallucinations on silent / noisy chunks). Set to
 * `true` only as an escape hatch — e.g. for very soft speakers
 * the model misclassifies as silence, or to reproduce pre-Silero
 * behaviour for benchmarking.
 */
disableNeuralVad: boolean | null }
/**
 * Identifier of a single streaming session. UUIDv7 keeps insertion
 * order ≈ creation order, useful for logs.
 */
export type StreamingSessionId = string
/**
 * A persisted LLM summary attached to a [`crate::Meeting`].
 * 
 * `serde(rename_all = "camelCase")` so the React layer can consume
 * `meetingId` / `createdAt` directly. The `content` field flattens
 * the [`SummaryContent`] enum so JSON readers see one combined
 * document instead of `{ "content": { … } }`, matching how the LLM
 * itself emits the structured output.
 */
export type Summary = 
/**
 * Structured payload — discriminated on `template`.
 */
(
/**
 * Default template — works for any meeting type (§3.2.1).
 */
{ template: "general"; summary: string; key_points?: string[]; decisions?: string[]; action_items?: ActionItem[]; open_questions?: string[] } | 
/**
 * 1:1 meetings between manager and report (§3.2.2).
 */
{ template: "oneOnOne"; summary: string; wins?: string[]; blockers?: string[]; growth_feedback?: string[]; next_steps?: ActionItem[]; follow_up_topics?: string[] } | 
/**
 * Sprint review / retrospective (§3.2.3).
 */
{ template: "sprintReview"; summary: string; completed_items?: string[]; carry_over?: string[]; risks?: string[]; next_sprint_priorities?: string[] } | 
/**
 * User research or hiring interview (§3.2.4).
 */
{ template: "interview"; summary: string; quotes?: InterviewQuote[]; themes?: string[]; pain_points?: string[]; opportunities?: string[] } | 
/**
 * Sales / discovery call (§3.2.5).
 */
{ template: "salesCall"; summary: string; customer_context?: string | null; pain_points?: string[]; interest_signals?: string[]; objections?: string[]; next_steps?: ActionItem[]; deal_stage_indicator?: string | null } | 
/**
 * Lecture, class, or workshop (§3.2.6).
 */
{ template: "lecture"; summary: string; concepts_covered?: string[]; definitions?: Definition[]; examples?: string[]; homework_or_next?: string[] } | 
/**
 * Graceful degradation when JSON parsing fails twice.
 */
{ template: "freeText"; text: string }) & { 
/**
 * Stable identifier.
 */
id: SummaryId; 
/**
 * Owning meeting. Each meeting may carry at most one summary
 * per template at a time — re-running the summarizer
 * overwrites the previous one (the SQLite adapter enforces
 * this with a unique index).
 */
meetingId: MeetingId; 
/**
 * LLM model identifier (e.g. `"qwen2.5-7b-instruct-q4_k_m"`).
 * Stored alongside the content so a future "regenerate with
 * model X" flow can compare provenance.
 */
model: string; 
/**
 * ISO-639-1 language the summary was produced in. Echoes the
 * transcript's dominant language; the LLM is instructed to
 * answer in that language.
 */
language: string | null; 
/**
 * RFC 3339 instant the summary finished generating.
 */
createdAt: string }
/**
 * Strongly-typed identifier for a [`Summary`]. UUIDv7 keeps lexical
 * ordering aligned with creation time, the same convention every
 * other id in this crate uses.
 */
export type SummaryId = string
export type TAURI_CHANNEL<TSend> = null
/**
 * One event emitted by the streaming pipeline.
 * 
 * The variant order on the wire intentionally matches the lifecycle:
 * `Started` → 0..N × `Chunk` → optional `Skipped` mixed in →
 * `Stopped` | `Failed`.
 * 
 * Wire format: tagged with `type` (lowercase) and field names in
 * `camelCase` for ergonomic consumption from TypeScript.
 */
export type TranscriptEvent = 
/**
 * Capture has begun. Reports the negotiated input format.
 */
{ type: "started"; sessionId: StreamingSessionId; inputFormat: AudioFormat } | 
/**
 * One transcribed chunk. Segments inside are timestamped relative
 * to the start of the session (not the chunk).
 */
{ type: "chunk"; sessionId: StreamingSessionId; chunkIndex: number; offsetMs: number; segments: Segment[]; language: string | null; rtf: number; speakerId?: SpeakerId | null; speakerSlot?: number | null } | 
/**
 * A chunk was discarded by the silence gate before being sent to
 * the ASR backend. Useful for UI / metrics.
 */
{ type: "skipped"; sessionId: StreamingSessionId; chunkIndex: number; offsetMs: number; durationMs: number; rms: number } | 
/**
 * The pipeline finished cleanly (caller stopped or stream EOF).
 */
{ type: "stopped"; sessionId: StreamingSessionId; totalSegments: number; totalAudioMs: number } | 
/**
 * The pipeline aborted with an error. No further events follow.
 */
{ type: "failed"; sessionId: StreamingSessionId; message: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
