//! Tauri IPC commands exposed to the frontend.
//!
//! Each `#[tauri::command]` function mirrors a typed contract in
//! `src/ipc/bindings.ts` (auto-generated by `tauri-specta`). The
//! commands are split into sub-modules by domain:
//!
//! - [`streaming`] — live transcription session lifecycle
//! - [`meetings`] — CRUD + search over persisted meetings
//! - [`llm`] — summary generation and transcript chat
//! - [`export`] — file export (Markdown / plain text)
//! - [`models`] — model catalog, status, and download

pub mod export;
pub mod hardware;
pub mod llm;
pub mod mcp;
pub mod meetings;
pub mod models;
pub mod recommendation;
pub mod streaming;
pub mod templates;

// Re-export public items for non-macro usage (e.g. `commands::AppState`).
// The `tauri_specta::collect_commands!` macro in `lib.rs` references
// sub-modules directly: `commands::streaming::start_streaming`, etc.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use serde::Serialize;
use time::{format_description::well_known::Rfc3339, OffsetDateTime};
use tokio::sync::Mutex as AsyncMutex;
use tokio::task::JoinHandle;

use crate::ipc_error::{ErrorCode, IpcError};

use echo_app::{MeetingRecorder, RenameSpeaker, StreamingHandle};
use echo_asr::WhisperCppTranscriber;
use echo_audio::{RoutingAudioCapture, RubatoResamplerAdapter, SileroVad};
use echo_diarize::{
    embedding::SpeakerEmbedder, CamPlusPlusEmbedder, Eres2NetEmbedder, OnlineDiarizer,
    PyannoteSegmenter,
};
use echo_domain::{
    AudioCapture, ChatAssistant, Diarizer, LlmModel, MeetingStore, Resampler, Transcriber,
};
use echo_llm::{LlamaCppLlm, LoadOptions as LlamaLoadOptions};
use echo_storage::SqliteMeetingStore;

// ---------------------------------------------------------------------------
// LazyModel<T> — generic lazy-init wrapper (ARCH-2)
// ---------------------------------------------------------------------------

/// A model slot that is loaded on first use and cached for the process
/// lifetime. Wraps `AsyncMutex<Option<Arc<T>>>` + `spawn_blocking` so
/// callers get a simple `get_or_init` API.
pub(crate) struct LazyModel<T> {
    inner: AsyncMutex<Option<Arc<T>>>,
}

impl<T: Send + Sync + 'static> LazyModel<T> {
    pub fn new() -> Self {
        Self {
            inner: AsyncMutex::new(None),
        }
    }

    /// Return the cached model, or initialize it by running the async
    /// `init` closure (which typically calls `spawn_blocking`).  The
    /// mutex is held across the init so concurrent callers queue
    /// behind the first load.
    pub async fn get_or_init<F, Fut, E>(&self, init: F) -> Result<Arc<T>, E>
    where
        F: FnOnce() -> Fut,
        Fut: std::future::Future<Output = Result<T, E>>,
    {
        let mut guard = self.inner.lock().await;
        if let Some(ref model) = *guard {
            return Ok(Arc::clone(model));
        }
        let model = init().await?;
        let arc = Arc::new(model);
        *guard = Some(Arc::clone(&arc));
        Ok(arc)
    }

    /// Drop the cached model, freeing its memory. The next call to
    /// `get_or_init` will re-load from disk. Returns `true` if a
    /// model was actually unloaded.
    pub async fn unload(&self) -> bool {
        self.inner.lock().await.take().is_some()
    }
}

// ---------------------------------------------------------------------------
// Health check (Sprint 0 day 4)
// ---------------------------------------------------------------------------

/// Result returned by [`health_check`]. Mirrors `HealthStatus` on the TS side.
#[derive(Debug, Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct HealthStatus {
    /// RFC 3339 timestamp of the probe.
    pub timestamp: String,
    /// Backend semver, from Cargo at compile time.
    pub version: String,
    /// Target triple the backend was compiled for.
    pub target: String,
    /// Short git hash, `unknown` when `.git` is missing at build time.
    pub commit: String,
}

/// Lightweight probe the frontend calls on mount to confirm the bridge is live.
#[tauri::command]
#[specta::specta]
pub fn health_check() -> HealthStatus {
    let timestamp = OffsetDateTime::now_utc()
        .format(&Rfc3339)
        .unwrap_or_else(|_| "unknown".to_string());

    HealthStatus {
        timestamp,
        version: env!("CARGO_PKG_VERSION").to_string(),
        target: env!("TAURI_ENV_TARGET_TRIPLE").to_string(),
        commit: env!("ECHO_GIT_HASH").to_string(),
    }
}

// ---------------------------------------------------------------------------
// AppState
// ---------------------------------------------------------------------------

/// Shared state injected through `tauri::Builder::manage`. Holds the
/// shared adapters so the model is loaded once per app session, the
/// SQLite-backed meeting store, the per-session meeting recorder and
/// the in-flight streaming sessions so they can be stopped from the UI.
pub struct AppState {
    pub(crate) capture: Arc<dyn AudioCapture>,
    pub(crate) resampler: Arc<dyn Resampler>,
    /// Lazily-loaded whisper transcriber (concrete so `LazyModel<T>` stays `Sized`).
    pub(crate) transcriber: LazyModel<WhisperCppTranscriber>,
    /// Path to the local ASR model. Behind a `RwLock` so
    /// `set_active_asr` can switch models at runtime.
    pub(crate) model_path: std::sync::RwLock<PathBuf>,
    /// Where to find the speaker embedder ONNX. Behind a `RwLock` so
    /// `set_active_embedder` can switch between ERes2Net and CAM++ at runtime.
    pub(crate) embed_model_path: std::sync::RwLock<PathBuf>,
    /// Where to find the pyannote segmentation ONNX (optional).
    /// When the file exists, `build_diarizer` attaches a
    /// `PyannoteSegmenter` to the `OnlineDiarizer` automatically.
    pub(crate) seg_model_path: PathBuf,
    pub(crate) store: Arc<dyn MeetingStore>,
    pub(crate) recorder: Arc<MeetingRecorder>,
    pub(crate) rename_speaker: Arc<RenameSpeaker>,
    /// In-flight streaming sessions.
    pub(crate) sessions: Arc<Mutex<HashMap<StreamingSessionId, SessionEntry>>>,
    /// Path to the local LLM (.gguf). Behind a `RwLock` so
    /// `set_active_llm` can switch models at runtime.
    pub(crate) llm_model_path: std::sync::RwLock<PathBuf>,
    /// Lazily-loaded LLM, held as the concrete [`LlamaCppLlm`] so we
    /// can derive both `LlmModel` and `ChatAssistant` from the same
    /// loaded weights.
    pub(crate) llm: LazyModel<LlamaCppLlm>,
    /// Path to the Silero VAD ONNX.
    pub(crate) vad_model_path: PathBuf,
    /// Lazily-loaded Silero VAD template.
    pub(crate) vad: LazyModel<SileroVad>,
    /// Model IDs currently being downloaded, mapped to a cancel flag.
    /// Setting the flag to `true` signals the download loop to abort.
    pub(crate) in_flight_downloads: Arc<
        Mutex<std::collections::HashMap<String, std::sync::Arc<std::sync::atomic::AtomicBool>>>,
    >,
    /// Root directory for model files and other data assets.
    /// In debug builds this is the workspace root; in release builds
    /// it falls back to the Tauri `appDataDir` so models are
    /// downloaded to a writable, OS-standard location.
    pub(crate) data_root: PathBuf,
}

use echo_domain::StreamingSessionId;

pub(crate) struct SessionEntry {
    pub join: JoinHandle<()>,
    pub handle: Arc<AsyncMutex<StreamingHandle>>,
    /// Shared pause flag extracted before wrapping the handle in a
    /// mutex.  `pause_streaming` / `resume_streaming` use this
    /// directly so they never contend with the drain loop's lock.
    pub paused: Arc<std::sync::atomic::AtomicBool>,
    /// RAII guard — prevents the OS from sleeping while recording.
    /// Dropped automatically when the session entry is removed.
    pub _keep_awake: Option<keepawake::KeepAwake>,
}

impl AppState {
    /// Cheap clone of the session-map handle.
    pub(crate) fn sessions_handle(&self) -> Arc<Mutex<HashMap<StreamingSessionId, SessionEntry>>> {
        self.sessions.clone()
    }

    /// Update the LLM model path at runtime. Must be called after
    /// `llm.unload()` so the next `ensure_llm()` loads the new model.
    pub(crate) fn set_llm_model_path(&self, path: PathBuf) {
        *self.llm_model_path.write().unwrap() = path;
    }

    /// Read the current LLM model path.
    pub(crate) fn active_llm_path(&self) -> PathBuf {
        self.llm_model_path.read().unwrap().clone()
    }

    /// Update the ASR model path at runtime. Must be called after
    /// `transcriber.unload()` so the next `ensure_transcriber()` loads
    /// the new model.
    pub(crate) fn set_asr_model_path(&self, path: PathBuf) {
        *self.model_path.write().unwrap() = path;
    }

    /// Read the current ASR model path.
    pub(crate) fn active_asr_path(&self) -> PathBuf {
        self.model_path.read().unwrap().clone()
    }

    /// Switch the embedder path. The next `build_diarizer` call picks it up.
    pub(crate) fn set_embed_model_path(&self, path: PathBuf) {
        *self.embed_model_path.write().unwrap() = path;
    }

    /// Read the current embedder path.
    pub(crate) fn active_embed_path(&self) -> PathBuf {
        self.embed_model_path.read().unwrap().clone()
    }

    /// Ordered shutdown sequence invoked from the Tauri `Exit` hook.
    pub async fn shutdown(&self) {
        let entries: Vec<SessionEntry> = match self.sessions.lock() {
            Ok(mut map) => map.drain().map(|(_, e)| e).collect(),
            Err(poisoned) => {
                tracing::warn!("shutdown: session map poisoned; recovering");
                poisoned.into_inner().drain().map(|(_, e)| e).collect()
            }
        };
        let pending = entries.len();
        if pending > 0 {
            tracing::info!(pending, "shutdown: stopping in-flight sessions");
        }
        for entry in entries {
            let mut handle = entry.handle.lock().await;
            if let Err(e) = handle.stop().await {
                tracing::warn!(error = %e, "shutdown: stop_streaming failed");
            }
            drop(handle);
            match tokio::time::timeout(std::time::Duration::from_secs(5), entry.join).await {
                Ok(Ok(())) => {}
                Ok(Err(e)) => tracing::warn!(error = %e, "shutdown: drain task panicked"),
                Err(_) => {
                    tracing::warn!("shutdown: drain task did not finish within 5s; abandoning")
                }
            }
        }
        // Flush WAL to the main database file before _exit() skips
        // normal cleanup. Without this, data written since the last
        // automatic checkpoint may be lost.
        if let Err(e) = self.store.checkpoint().await {
            tracing::warn!(error = %e, "shutdown: WAL checkpoint failed");
        }
        self.store.close().await;
        tracing::info!("shutdown: complete");
    }

    /// Build the shared state. Async because opening the SQLite database
    /// runs migrations, which is I/O.
    pub async fn initialize(app_data_dir: Option<PathBuf>) -> Result<Self, IpcError> {
        // In release builds prefer the Tauri app-data directory so
        // downloaded models land in an OS-writable location instead of
        // the (non-existent) compile-time source tree.
        let data_root = if cfg!(debug_assertions) {
            workspace_root()
        } else {
            app_data_dir.clone().unwrap_or_else(workspace_root)
        };
        tracing::info!(data_root = %data_root.display(), "resolved data root for model assets");

        // In debug builds, allow ECHO_*_MODEL env vars to override
        // asset paths for development convenience. In release builds
        // these are ignored to prevent path-hijack via environment
        // variable manipulation.
        let env_override = |key: &str| -> Option<String> {
            if cfg!(debug_assertions) {
                std::env::var(key).ok()
            } else {
                None
            }
        };

        let model_path = resolve_asset_path(
            &data_root,
            env_override("ECHO_ASR_MODEL"),
            preferred_asr_model(&data_root),
        );
        let embed_model_path = resolve_asset_path(
            &data_root,
            env_override("ECHO_EMBED_MODEL"),
            preferred_embed_model(&data_root),
        );
        let seg_model_path = resolve_asset_path(
            &data_root,
            env_override("ECHO_SEG_MODEL"),
            "models/segmenter/pyannote_segmentation_3.onnx",
        );
        let llm_model_path = resolve_asset_path(
            &data_root,
            env_override("ECHO_LLM_MODEL"),
            preferred_llm_model(&data_root),
        );
        let vad_model_path = resolve_asset_path(
            &data_root,
            env_override("ECHO_VAD_MODEL"),
            "models/vad/silero_vad.onnx",
        );

        let db_path = resolve_db_path(app_data_dir);
        tracing::info!(
            asr_model = %model_path.display(),
            embed_model = %embed_model_path.display(),
            seg_model = %seg_model_path.display(),
            llm_model = %llm_model_path.display(),
            vad_model = %vad_model_path.display(),
            db_path = %db_path.display(),
            "echo-shell paths resolved"
        );
        let store = SqliteMeetingStore::open(&db_path).await.map_err(|e| {
            IpcError::storage(format!("open meeting store at {}: {e}", db_path.display()))
        })?;
        tracing::info!(db_path = %db_path.display(), "meeting store ready");

        let store: Arc<dyn MeetingStore> = Arc::new(store);
        let recorder = Arc::new(MeetingRecorder::with_default_title(store.clone()));
        let rename_speaker = Arc::new(RenameSpeaker::new(store.clone()));

        Ok(Self {
            capture: Arc::new(RoutingAudioCapture::with_default_adapters()),
            resampler: Arc::new(RubatoResamplerAdapter::new()),
            transcriber: LazyModel::new(),
            model_path: std::sync::RwLock::new(model_path),
            embed_model_path: std::sync::RwLock::new(embed_model_path),
            seg_model_path,
            store,
            recorder,
            rename_speaker,
            sessions: Arc::new(Mutex::new(HashMap::new())),
            llm_model_path: std::sync::RwLock::new(llm_model_path),
            llm: LazyModel::new(),
            vad_model_path,
            vad: LazyModel::new(),
            in_flight_downloads: Arc::new(Mutex::new(std::collections::HashMap::new())),
            data_root,
        })
    }

    // -----------------------------------------------------------------
    // Lazy model accessors
    // -----------------------------------------------------------------

    /// Lazily load the local LLM (concrete type for adapters).
    pub(crate) async fn ensure_llm_concrete(&self) -> Result<Arc<LlamaCppLlm>, IpcError> {
        let model_path = self.llm_model_path.read().unwrap().clone();
        let data_root = self.data_root.clone();
        self.llm
            .get_or_init(|| async move {
                let path = if model_path.exists() {
                    model_path.clone()
                } else {
                    let env_llm = if cfg!(debug_assertions) {
                        std::env::var("ECHO_LLM_MODEL").ok()
                    } else {
                        None
                    };
                    let fresh = resolve_asset_path(
                        &data_root,
                        env_llm,
                        preferred_llm_model(&data_root),
                    );
                    if !fresh.exists() {
                        return Err(IpcError::model_not_ready(
                            "No language model installed. Open the Models panel and download one to enable summaries and chat."
                                .to_string(),
                        ));
                    }
                    tracing::info!(path = %fresh.display(), "re-resolved LLM path after runtime download");
                    fresh
                };
                let load_opts = LlamaLoadOptions::default();
                tokio::task::spawn_blocking({
                    let path = path.clone();
                    move || LlamaCppLlm::load_with(&path, load_opts)
                })
                .await
                .map_err(|e| IpcError::internal(format!("LLM load task panicked: {e}")))?
                .map_err(|e| {
                    IpcError::new(
                        ErrorCode::Llm,
                        format!("failed to load LLM at {}: {e}", path.display()),
                    )
                })
            })
            .await
    }

    /// Lazy `LlmModel` accessor for summarize.
    pub(crate) async fn ensure_llm(&self) -> Result<Arc<dyn LlmModel>, IpcError> {
        Ok(self.ensure_llm_concrete().await? as Arc<dyn LlmModel>)
    }

    /// Lazy `ChatAssistant` accessor for chat.
    pub(crate) async fn ensure_chat(&self) -> Result<Arc<dyn ChatAssistant>, IpcError> {
        let llm = self.ensure_llm_concrete().await?;
        Ok(Arc::new(llm.chat_handle()) as Arc<dyn ChatAssistant>)
    }

    /// Build a fresh diarizer for the upcoming session.
    ///
    /// Embedder selection: if the resolved path filename contains
    /// "camplusplus" or "campplus", `CamPlusPlusEmbedder` is loaded;
    /// otherwise `Eres2NetEmbedder` is used. The pyannote segmenter is
    /// attached automatically when its model file is present on disk.
    pub(crate) fn build_diarizer(
        &self,
        override_path: Option<PathBuf>,
    ) -> Result<Box<dyn Diarizer>, IpcError> {
        let path = override_path.unwrap_or_else(|| self.active_embed_path());
        if !path.exists() {
            return Err(IpcError::model_not_ready(
                "Speaker embedder model not installed. Open the Models panel and download ERes2Net or CAM++ to enable speaker identification."
                    .to_string(),
            ));
        }

        let file_name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        let started = std::time::Instant::now();
        let embedder: Box<dyn SpeakerEmbedder> =
            if file_name.contains("camplusplus") || file_name.contains("campplus") {
                let emb = CamPlusPlusEmbedder::new(&path).map_err(|e| {
                    IpcError::new(
                        ErrorCode::Diarization,
                        format!("load CAM++ at {}: {e}", path.display()),
                    )
                })?;
                tracing::info!(
                    model = %path.display(),
                    load_ms = started.elapsed().as_millis() as u64,
                    "CAM++ speaker embedder ready"
                );
                Box::new(emb)
            } else {
                let emb = Eres2NetEmbedder::new(&path).map_err(|e| {
                    IpcError::new(
                        ErrorCode::Diarization,
                        format!("load ERes2Net at {}: {e}", path.display()),
                    )
                })?;
                tracing::info!(
                    model = %path.display(),
                    load_ms = started.elapsed().as_millis() as u64,
                    "ERes2Net speaker embedder ready"
                );
                Box::new(emb)
            };

        // CAM++ 512-dim embeddings have a higher cross-speaker baseline
        // than ERes2Net 192-dim. In controlled English fixtures
        // cross-speaker cosine is ~0.57, but real-world Spanish podcasts
        // (same mic, same gender, similar timbre) can push cross-speaker
        // to 0.70–0.78. We set:
        //   - similarity_threshold = 0.78: high enough to separate same-
        //     gender speakers sharing a mic, low enough that the same
        //     speaker's centroids don't over-split.
        //   - merge_threshold = 1.0: DISABLE online centroid merging.
        //     The EMA centroids drift toward each other over time, and at
        //     0.85 they cascade-merge all speakers into one. The offline
        //     AHC pass (refine_offline) handles merging properly after the
        //     session ends, using full-session means instead of noisy EMAs.
        let cluster_cfg = if file_name.contains("camplusplus") || file_name.contains("campplus") {
            echo_diarize::OnlineClusterConfig {
                similarity_threshold: 0.78,
                merge_threshold: 1.0, // disable online merge for CAM++
                ..Default::default()
            }
        } else {
            echo_diarize::OnlineClusterConfig::default()
        };
        let mut diarizer = OnlineDiarizer::new(embedder, cluster_cfg);

        // Attach pyannote segmenter if the model file is installed.
        if self.seg_model_path.exists() {
            match PyannoteSegmenter::new(&self.seg_model_path) {
                Ok(seg) => {
                    tracing::info!(
                        model = %self.seg_model_path.display(),
                        "pyannote segmenter attached — sub-chunk speaker boundaries enabled"
                    );
                    diarizer = diarizer.with_segmenter(Box::new(seg));
                }
                Err(e) => {
                    tracing::warn!(
                        error = %e,
                        model = %self.seg_model_path.display(),
                        "failed to load pyannote segmenter; continuing without sub-chunk segmentation"
                    );
                }
            }
        }

        Ok(Box::new(diarizer))
    }

    /// Lazily load the Silero VAD ONNX once per process.
    ///
    /// Returns `Ok(None)` when the model file is missing — callers
    /// fall back to the pure-RMS silence gate.
    pub(crate) async fn ensure_vad(&self) -> Result<Option<Arc<SileroVad>>, IpcError> {
        if !self.vad_model_path.exists() {
            tracing::warn!(
                vad_model = %self.vad_model_path.display(),
                "Silero VAD model not installed; falling back to RMS gate. \
                 Download it from the Models panel for better voice detection."
            );
            return Ok(None);
        }
        let vad_path = self.vad_model_path.clone();
        let arc = self
            .vad
            .get_or_init(|| async move {
                let started = std::time::Instant::now();
                let path = vad_path.clone();
                let loaded = tokio::task::spawn_blocking(move || SileroVad::for_meetings(&path))
                    .await
                    .map_err(|e| IpcError::internal(format!("Silero VAD load task panicked: {e}")))?
                    .map_err(|e| {
                        IpcError::new(
                            ErrorCode::Vad,
                            format!("failed to load Silero VAD at {}: {e}", vad_path.display()),
                        )
                    })?;
                tracing::info!(
                    vad_model = %vad_path.display(),
                    load_ms = started.elapsed().as_millis() as u64,
                    "Silero VAD ready"
                );
                Ok::<SileroVad, IpcError>(loaded)
            })
            .await?;
        Ok(Some(arc))
    }

    /// Lazily load the whisper transcriber.
    pub(crate) async fn ensure_transcriber(&self) -> Result<Arc<dyn Transcriber>, IpcError> {
        let asr_path = self.model_path.read().unwrap().clone();
        let data_root = self.data_root.clone();
        self.transcriber
            .get_or_init(|| async move {
                let path = if asr_path.exists() {
                    asr_path.clone()
                } else {
                    let env_asr = if cfg!(debug_assertions) {
                        std::env::var("ECHO_ASR_MODEL").ok()
                    } else {
                        None
                    };
                    let fresh = resolve_asset_path(
                        &data_root,
                        env_asr,
                        preferred_asr_model(&data_root),
                    );
                    if !fresh.exists() {
                        return Err(IpcError::model_not_ready(
                            "No speech recognition model installed. Open the Models panel and download a Whisper model to start transcribing."
                                .to_string(),
                        ));
                    }
                    tracing::info!(path = %fresh.display(), "re-resolved ASR path after runtime download");
                    fresh
                };
                let loaded =
                    tokio::task::spawn_blocking(move || WhisperCppTranscriber::load(&path))
                        .await
                        .map_err(|e| {
                            IpcError::internal(format!("whisper load task panicked: {e}"))
                        })?
                        .map_err(|e| {
                            IpcError::new(
                                ErrorCode::Asr,
                                format!("failed to load whisper model: {e}"),
                            )
                        })?;
                Ok(loaded)
            })
            .await
            .map(|arc| arc as Arc<dyn Transcriber>)
    }
}

// ---------------------------------------------------------------------------
// Path helpers (crate-internal, used by sub-modules via `super::`)
// ---------------------------------------------------------------------------

fn resolve_db_path(app_data_dir: Option<PathBuf>) -> PathBuf {
    // Only honour ECHO_DB_PATH in debug builds to prevent
    // environment-based path hijacking in production.
    if cfg!(debug_assertions) {
        if let Some(raw) = std::env::var("ECHO_DB_PATH")
            .ok()
            .filter(|s| !s.trim().is_empty())
        {
            let p = PathBuf::from(&raw);
            if p.is_absolute() {
                return p;
            }
            let rooted = workspace_root().join(&p);
            if rooted.exists() {
                return rooted;
            }
            return p;
        }
    }
    if let Some(dir) = app_data_dir {
        return dir.join("echonote.db");
    }
    workspace_root().join("echonote.db")
}

fn preferred_llm_model(root: &Path) -> &'static str {
    const CANDIDATES: &[&str] = &[
        "models/llm/Qwen3-30B-A3B-Q4_K_M.gguf",
        "models/llm/Qwen3-14B-Q4_K_M.gguf",
        "models/llm/Qwen3-8B-Q4_K_M.gguf",
        "models/llm/Qwen3-4B-Q4_K_M.gguf",
        "models/llm/qwen2.5-7b-instruct-q4_k_m.gguf",
        "models/llm/qwen2.5-3b-instruct-q4_k_m.gguf",
    ];
    // Honour persisted preference if present and still downloaded.
    if let Some(pref_path) = load_preference(root, "llm") {
        for &candidate in CANDIDATES {
            if candidate == pref_path && root.join(candidate).exists() {
                return candidate;
            }
        }
    }
    for rel in CANDIDATES {
        if root.join(rel).exists() {
            return rel;
        }
    }
    "models/llm/Qwen3-14B-Q4_K_M.gguf"
}

fn preferred_embed_model(root: &Path) -> &'static str {
    // If the user persisted a preference, honour it.
    if let Some(pref_path) = load_preference(root, "embedder") {
        // The preference stores the relative path directly.
        // Match against known static paths to return &'static str.
        const KNOWN: &[&str] = &[
            "models/embedder/campplus_en_voxceleb.onnx",
            "models/embedder/eres2net_en_voxceleb.onnx",
        ];
        for &candidate in KNOWN {
            if candidate == pref_path && root.join(candidate).exists() {
                return candidate;
            }
        }
    }
    // CAM++ has lower EER and better multilingual coverage than ERes2Net,
    // so prefer it when already installed.
    const CANDIDATES: &[&str] = &[
        "models/embedder/campplus_en_voxceleb.onnx",
        "models/embedder/eres2net_en_voxceleb.onnx",
    ];
    for rel in CANDIDATES {
        if root.join(rel).exists() {
            return rel;
        }
    }
    "models/embedder/eres2net_en_voxceleb.onnx"
}

fn preferred_asr_model(root: &Path) -> &'static str {
    const CANDIDATES: &[&str] = &[
        "models/asr/ggml-large-v3-turbo-es.bin",
        "models/asr/ggml-large-v3-turbo.bin",
        "models/asr/ggml-large-v3-turbo-q5_0.bin",
        "models/asr/ggml-large-v3.bin",
        "models/asr/ggml-medium.bin",
        "models/asr/ggml-small.bin",
        "models/asr/ggml-base.bin",
        "models/asr/ggml-tiny.bin",
        "models/asr/ggml-distil-large-v3.bin",
        "models/asr/ggml-base.en.bin",
        "models/asr/ggml-small.en.bin",
        "models/asr/ggml-tiny.en.bin",
    ];
    // Honour persisted preference if present and still downloaded.
    if let Some(pref_path) = load_preference(root, "asr") {
        for &candidate in CANDIDATES {
            if candidate == pref_path && root.join(candidate).exists() {
                return candidate;
            }
        }
    }
    for rel in CANDIDATES {
        if root.join(rel).exists() {
            return rel;
        }
    }
    "models/asr/ggml-large-v3-turbo.bin"
}

fn resolve_asset_path(
    root: &Path,
    override_value: Option<String>,
    default_relative: &str,
) -> PathBuf {
    if let Some(raw) = override_value.filter(|s| !s.trim().is_empty()) {
        let raw_path = PathBuf::from(&raw);
        if raw_path.is_absolute() {
            return raw_path;
        }
        let rooted = root.join(&raw_path);
        if rooted.exists() {
            return rooted;
        }
        return raw_path;
    }

    root.join(default_relative)
}

/// Best-effort workspace root: the directory above `src-tauri/`.
pub(crate) fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(PathBuf::from)
        .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")))
}

// ---------------------------------------------------------------------------
// Model preference persistence
// ---------------------------------------------------------------------------

/// Preferences file path: `<data_root>/model_preferences.json`
fn preferences_path(root: &Path) -> PathBuf {
    root.join("model_preferences.json")
}

/// Load a persisted model preference by key (e.g. "embedder", "asr", "llm").
/// Returns `None` if the file doesn't exist or the key is absent.
fn load_preference(root: &Path, key: &str) -> Option<String> {
    let path = preferences_path(root);
    let content = std::fs::read_to_string(&path).ok()?;
    let map: serde_json::Map<String, serde_json::Value> = serde_json::from_str(&content).ok()?;
    map.get(key)?.as_str().map(String::from)
}

/// Persist a model preference. Merges with existing preferences.
pub(crate) fn save_preference(root: &Path, key: &str, value: &str) {
    let path = preferences_path(root);
    let mut map: serde_json::Map<String, serde_json::Value> = std::fs::read_to_string(&path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default();
    map.insert(
        key.to_string(),
        serde_json::Value::String(value.to_string()),
    );
    if let Ok(json) = serde_json::to_string_pretty(&map) {
        let _ = std::fs::write(&path, json);
    }
}
