//! Tauri IPC commands exposed to the frontend.
//!
//! Each `#[tauri::command]` function mirrors a typed contract in
//! `src/ipc/bindings.ts` (auto-generated by `tauri-specta`). The
//! commands are split into sub-modules by domain:
//!
//! - [`streaming`] — live transcription session lifecycle
//! - [`meetings`] — CRUD + search over persisted meetings
//! - [`llm`] — summary generation and transcript chat
//! - [`export`] — file export (Markdown / plain text)
//! - [`models`] — model catalog, status, and download

pub mod export;
pub mod llm;
pub mod meetings;
pub mod models;
pub mod streaming;

// Re-export public items for non-macro usage (e.g. `commands::AppState`).
// The `tauri_specta::collect_commands!` macro in `lib.rs` references
// sub-modules directly: `commands::streaming::start_streaming`, etc.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use serde::Serialize;
use time::{format_description::well_known::Rfc3339, OffsetDateTime};
use tokio::sync::Mutex as AsyncMutex;
use tokio::task::JoinHandle;

use crate::ipc_error::{ErrorCode, IpcError};

use echo_app::{MeetingRecorder, RenameSpeaker, StreamingHandle};
use echo_asr::WhisperCppTranscriber;
use echo_audio::{RoutingAudioCapture, RubatoResamplerAdapter, SileroVad};
use echo_diarize::{Eres2NetEmbedder, OnlineDiarizer};
use echo_domain::{
    AudioCapture, ChatAssistant, Diarizer, LlmModel, MeetingStore, Resampler, Transcriber,
};
use echo_llm::{LlamaCppLlm, LoadOptions as LlamaLoadOptions};
use echo_storage::SqliteMeetingStore;

// ---------------------------------------------------------------------------
// LazyModel<T> — generic lazy-init wrapper (ARCH-2)
// ---------------------------------------------------------------------------

/// A model slot that is loaded on first use and cached for the process
/// lifetime. Wraps `AsyncMutex<Option<Arc<T>>>` + `spawn_blocking` so
/// callers get a simple `get_or_init` API.
pub(crate) struct LazyModel<T> {
    inner: AsyncMutex<Option<Arc<T>>>,
}

impl<T: Send + Sync + 'static> LazyModel<T> {
    pub fn new() -> Self {
        Self {
            inner: AsyncMutex::new(None),
        }
    }

    /// Return the cached model, or initialize it by running the async
    /// `init` closure (which typically calls `spawn_blocking`).  The
    /// mutex is held across the init so concurrent callers queue
    /// behind the first load.
    pub async fn get_or_init<F, Fut, E>(&self, init: F) -> Result<Arc<T>, E>
    where
        F: FnOnce() -> Fut,
        Fut: std::future::Future<Output = Result<T, E>>,
    {
        let mut guard = self.inner.lock().await;
        if let Some(ref model) = *guard {
            return Ok(Arc::clone(model));
        }
        let model = init().await?;
        let arc = Arc::new(model);
        *guard = Some(Arc::clone(&arc));
        Ok(arc)
    }
}

// ---------------------------------------------------------------------------
// Health check (Sprint 0 day 4)
// ---------------------------------------------------------------------------

/// Result returned by [`health_check`]. Mirrors `HealthStatus` on the TS side.
#[derive(Debug, Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct HealthStatus {
    /// RFC 3339 timestamp of the probe.
    pub timestamp: String,
    /// Backend semver, from Cargo at compile time.
    pub version: String,
    /// Target triple the backend was compiled for.
    pub target: String,
    /// Short git hash, `unknown` when `.git` is missing at build time.
    pub commit: String,
}

/// Lightweight probe the frontend calls on mount to confirm the bridge is live.
#[tauri::command]
#[specta::specta]
pub fn health_check() -> HealthStatus {
    let timestamp = OffsetDateTime::now_utc()
        .format(&Rfc3339)
        .unwrap_or_else(|_| "unknown".to_string());

    HealthStatus {
        timestamp,
        version: env!("CARGO_PKG_VERSION").to_string(),
        target: env!("TAURI_ENV_TARGET_TRIPLE").to_string(),
        commit: env!("ECHO_GIT_HASH").to_string(),
    }
}

// ---------------------------------------------------------------------------
// AppState
// ---------------------------------------------------------------------------

/// Shared state injected through `tauri::Builder::manage`. Holds the
/// shared adapters so the model is loaded once per app session, the
/// SQLite-backed meeting store, the per-session meeting recorder and
/// the in-flight streaming sessions so they can be stopped from the UI.
pub struct AppState {
    pub(crate) capture: Arc<dyn AudioCapture>,
    pub(crate) resampler: Arc<dyn Resampler>,
    /// Lazily-loaded whisper transcriber (concrete so `LazyModel<T>` stays `Sized`).
    pub(crate) transcriber: LazyModel<WhisperCppTranscriber>,
    pub(crate) model_path: PathBuf,
    /// Where to find the speaker embedder ONNX.
    pub(crate) embed_model_path: PathBuf,
    pub(crate) store: Arc<dyn MeetingStore>,
    pub(crate) recorder: Arc<MeetingRecorder>,
    pub(crate) rename_speaker: Arc<RenameSpeaker>,
    /// In-flight streaming sessions.
    pub(crate) sessions: Arc<Mutex<HashMap<StreamingSessionId, SessionEntry>>>,
    /// Path to the local LLM (.gguf).
    pub(crate) llm_model_path: PathBuf,
    /// Lazily-loaded LLM, held as the concrete [`LlamaCppLlm`] so we
    /// can derive both `LlmModel` and `ChatAssistant` from the same
    /// loaded weights.
    pub(crate) llm: LazyModel<LlamaCppLlm>,
    /// Path to the Silero VAD ONNX.
    pub(crate) vad_model_path: PathBuf,
    /// Lazily-loaded Silero VAD template.
    pub(crate) vad: LazyModel<SileroVad>,
}

use echo_domain::StreamingSessionId;

pub(crate) struct SessionEntry {
    pub join: JoinHandle<()>,
    pub handle: Arc<AsyncMutex<StreamingHandle>>,
}

impl AppState {
    /// Cheap clone of the session-map handle.
    pub(crate) fn sessions_handle(&self) -> Arc<Mutex<HashMap<StreamingSessionId, SessionEntry>>> {
        self.sessions.clone()
    }

    /// Ordered shutdown sequence invoked from the Tauri `Exit` hook.
    pub async fn shutdown(&self) {
        let entries: Vec<SessionEntry> = match self.sessions.lock() {
            Ok(mut map) => map.drain().map(|(_, e)| e).collect(),
            Err(poisoned) => {
                tracing::warn!("shutdown: session map poisoned; recovering");
                poisoned.into_inner().drain().map(|(_, e)| e).collect()
            }
        };
        let pending = entries.len();
        if pending > 0 {
            tracing::info!(pending, "shutdown: stopping in-flight sessions");
        }
        for entry in entries {
            let mut handle = entry.handle.lock().await;
            if let Err(e) = handle.stop().await {
                tracing::warn!(error = %e, "shutdown: stop_streaming failed");
            }
            drop(handle);
            match tokio::time::timeout(std::time::Duration::from_secs(5), entry.join).await {
                Ok(Ok(())) => {}
                Ok(Err(e)) => tracing::warn!(error = %e, "shutdown: drain task panicked"),
                Err(_) => {
                    tracing::warn!("shutdown: drain task did not finish within 5s; abandoning")
                }
            }
        }
        self.store.close().await;
        tracing::info!("shutdown: complete");
    }

    /// Build the shared state. Async because opening the SQLite database
    /// runs migrations, which is I/O.
    pub async fn initialize(app_data_dir: Option<PathBuf>) -> Result<Self, IpcError> {
        let model_path =
            resolve_asset_path(std::env::var("ECHO_ASR_MODEL").ok(), preferred_asr_model());
        let embed_model_path = resolve_asset_path(
            std::env::var("ECHO_EMBED_MODEL").ok(),
            "models/embedder/eres2net_en_voxceleb.onnx",
        );
        let llm_model_path =
            resolve_asset_path(std::env::var("ECHO_LLM_MODEL").ok(), preferred_llm_model());
        let vad_model_path = resolve_asset_path(
            std::env::var("ECHO_VAD_MODEL").ok(),
            "models/vad/silero_vad.onnx",
        );

        let db_path = resolve_db_path(app_data_dir);
        tracing::info!(
            asr_model = %model_path.display(),
            embed_model = %embed_model_path.display(),
            llm_model = %llm_model_path.display(),
            vad_model = %vad_model_path.display(),
            db_path = %db_path.display(),
            "echo-shell paths resolved"
        );
        let store = SqliteMeetingStore::open(&db_path).await.map_err(|e| {
            IpcError::storage(format!("open meeting store at {}: {e}", db_path.display()))
        })?;
        tracing::info!(db_path = %db_path.display(), "meeting store ready");

        let store: Arc<dyn MeetingStore> = Arc::new(store);
        let recorder = Arc::new(MeetingRecorder::with_default_title(store.clone()));
        let rename_speaker = Arc::new(RenameSpeaker::new(store.clone()));

        Ok(Self {
            capture: Arc::new(RoutingAudioCapture::with_default_adapters()),
            resampler: Arc::new(RubatoResamplerAdapter::new()),
            transcriber: LazyModel::new(),
            model_path,
            embed_model_path,
            store,
            recorder,
            rename_speaker,
            sessions: Arc::new(Mutex::new(HashMap::new())),
            llm_model_path,
            llm: LazyModel::new(),
            vad_model_path,
            vad: LazyModel::new(),
        })
    }

    // -----------------------------------------------------------------
    // Lazy model accessors
    // -----------------------------------------------------------------

    /// Lazily load the local LLM (concrete type for adapters).
    pub(crate) async fn ensure_llm_concrete(&self) -> Result<Arc<LlamaCppLlm>, IpcError> {
        let model_path = self.llm_model_path.clone();
        self.llm
            .get_or_init(|| async move {
                let path = if model_path.exists() {
                    model_path.clone()
                } else {
                    let fresh = resolve_asset_path(
                        std::env::var("ECHO_LLM_MODEL").ok(),
                        preferred_llm_model(),
                    );
                    if !fresh.exists() {
                        return Err(IpcError::model_not_ready(format!(
                            "LLM model not found at {}. Download one from the Models panel \
                             or run `scripts/download-models.sh llm`.",
                            model_path.display()
                        )));
                    }
                    tracing::info!(path = %fresh.display(), "re-resolved LLM path after runtime download");
                    fresh
                };
                let load_opts = LlamaLoadOptions::default();
                tokio::task::spawn_blocking({
                    let path = path.clone();
                    move || LlamaCppLlm::load_with(&path, load_opts)
                })
                .await
                .map_err(|e| IpcError::internal(format!("LLM load task panicked: {e}")))?
                .map_err(|e| {
                    IpcError::new(
                        ErrorCode::Llm,
                        format!("failed to load LLM at {}: {e}", path.display()),
                    )
                })
            })
            .await
    }

    /// Lazy `LlmModel` accessor for summarize.
    pub(crate) async fn ensure_llm(&self) -> Result<Arc<dyn LlmModel>, IpcError> {
        Ok(self.ensure_llm_concrete().await? as Arc<dyn LlmModel>)
    }

    /// Lazy `ChatAssistant` accessor for chat.
    pub(crate) async fn ensure_chat(&self) -> Result<Arc<dyn ChatAssistant>, IpcError> {
        let llm = self.ensure_llm_concrete().await?;
        Ok(Arc::new(llm.chat_handle()) as Arc<dyn ChatAssistant>)
    }

    /// Build a fresh diarizer for the upcoming session.
    pub(crate) fn build_diarizer(
        &self,
        override_path: Option<PathBuf>,
    ) -> Result<Box<dyn Diarizer>, IpcError> {
        let path = override_path.unwrap_or_else(|| self.embed_model_path.clone());
        if !path.exists() {
            return Err(IpcError::model_not_ready(format!(
                "speaker embedder not found at {}. Run `scripts/download-models.sh embed` \
                 or set ECHO_EMBED_MODEL.",
                path.display()
            )));
        }
        let started = std::time::Instant::now();
        let embedder = Eres2NetEmbedder::new(&path).map_err(|e| {
            IpcError::new(
                ErrorCode::Diarization,
                format!("load speaker embedder at {}: {e}", path.display()),
            )
        })?;
        tracing::info!(
            model = %path.display(),
            load_ms = started.elapsed().as_millis() as u64,
            "speaker embedder ready"
        );
        Ok(Box::new(OnlineDiarizer::with_defaults(Box::new(embedder))))
    }

    /// Lazily load the Silero VAD ONNX once per process.
    ///
    /// Returns `Ok(None)` when the model file is missing — callers
    /// fall back to the pure-RMS silence gate.
    pub(crate) async fn ensure_vad(&self) -> Result<Option<Arc<SileroVad>>, IpcError> {
        if !self.vad_model_path.exists() {
            tracing::warn!(
                vad_model = %self.vad_model_path.display(),
                "Silero VAD model not found; falling back to RMS gate. Run \
                 `scripts/download-models.sh vad` for sharper voice/non-voice \
                 discrimination (recommended)."
            );
            return Ok(None);
        }
        let vad_path = self.vad_model_path.clone();
        let arc = self
            .vad
            .get_or_init(|| async move {
                let started = std::time::Instant::now();
                let path = vad_path.clone();
                let loaded = tokio::task::spawn_blocking(move || SileroVad::for_meetings(&path))
                    .await
                    .map_err(|e| IpcError::internal(format!("Silero VAD load task panicked: {e}")))?
                    .map_err(|e| {
                        IpcError::new(
                            ErrorCode::Vad,
                            format!("failed to load Silero VAD at {}: {e}", vad_path.display()),
                        )
                    })?;
                tracing::info!(
                    vad_model = %vad_path.display(),
                    load_ms = started.elapsed().as_millis() as u64,
                    "Silero VAD ready"
                );
                Ok::<SileroVad, IpcError>(loaded)
            })
            .await?;
        Ok(Some(arc))
    }

    /// Lazily load the whisper transcriber.
    pub(crate) async fn ensure_transcriber(&self) -> Result<Arc<dyn Transcriber>, IpcError> {
        let asr_path = self.model_path.clone();
        self.transcriber
            .get_or_init(|| async move {
                let path = if asr_path.exists() {
                    asr_path.clone()
                } else {
                    let fresh = resolve_asset_path(
                        std::env::var("ECHO_ASR_MODEL").ok(),
                        preferred_asr_model(),
                    );
                    if !fresh.exists() {
                        return Err(IpcError::model_not_ready(format!(
                            "ASR model not found at {}. Download one from the Models panel \
                             or run `scripts/download-models.sh`.",
                            asr_path.display()
                        )));
                    }
                    tracing::info!(path = %fresh.display(), "re-resolved ASR path after runtime download");
                    fresh
                };
                let loaded =
                    tokio::task::spawn_blocking(move || WhisperCppTranscriber::load(&path))
                        .await
                        .map_err(|e| {
                            IpcError::internal(format!("whisper load task panicked: {e}"))
                        })?
                        .map_err(|e| {
                            IpcError::new(
                                ErrorCode::Asr,
                                format!("failed to load whisper model: {e}"),
                            )
                        })?;
                Ok(loaded)
            })
            .await
            .map(|arc| arc as Arc<dyn Transcriber>)
    }
}

// ---------------------------------------------------------------------------
// Path helpers (crate-internal, used by sub-modules via `super::`)
// ---------------------------------------------------------------------------

fn resolve_db_path(app_data_dir: Option<PathBuf>) -> PathBuf {
    if let Some(raw) = std::env::var("ECHO_DB_PATH")
        .ok()
        .filter(|s| !s.trim().is_empty())
    {
        let p = PathBuf::from(&raw);
        if p.is_absolute() {
            return p;
        }
        let rooted = workspace_root().join(&p);
        if rooted.exists() {
            return rooted;
        }
        return p;
    }
    if let Some(dir) = app_data_dir {
        return dir.join("echonote.db");
    }
    workspace_root().join("echonote.db")
}

fn preferred_llm_model() -> &'static str {
    const CANDIDATES: &[&str] = &[
        "models/llm/Qwen3-30B-A3B-Q4_K_M.gguf",
        "models/llm/Qwen3-14B-Q4_K_M.gguf",
        "models/llm/Qwen3-8B-Q4_K_M.gguf",
        "models/llm/qwen2.5-7b-instruct-q4_k_m.gguf",
        "models/llm/qwen2.5-3b-instruct-q4_k_m.gguf",
    ];
    let root = workspace_root();
    for rel in CANDIDATES {
        if root.join(rel).exists() {
            return rel;
        }
    }
    "models/llm/Qwen3-14B-Q4_K_M.gguf"
}

fn preferred_asr_model() -> &'static str {
    const CANDIDATES: &[&str] = &[
        "models/asr/ggml-large-v3-turbo-es.bin",
        "models/asr/ggml-large-v3-turbo.bin",
        "models/asr/ggml-large-v3-turbo-q5_0.bin",
        "models/asr/ggml-large-v3.bin",
        "models/asr/ggml-medium.bin",
        "models/asr/ggml-small.bin",
        "models/asr/ggml-base.bin",
        "models/asr/ggml-tiny.bin",
        "models/asr/ggml-distil-large-v3.bin",
        "models/asr/ggml-base.en.bin",
        "models/asr/ggml-small.en.bin",
        "models/asr/ggml-tiny.en.bin",
    ];
    let root = workspace_root();
    for rel in CANDIDATES {
        if root.join(rel).exists() {
            return rel;
        }
    }
    "models/asr/ggml-large-v3-turbo.bin"
}

fn resolve_asset_path(override_value: Option<String>, default_relative: &str) -> PathBuf {
    let workspace_root = workspace_root();

    if let Some(raw) = override_value.filter(|s| !s.trim().is_empty()) {
        let raw_path = PathBuf::from(&raw);
        if raw_path.is_absolute() {
            return raw_path;
        }
        let rooted = workspace_root.join(&raw_path);
        if rooted.exists() {
            return rooted;
        }
        return raw_path;
    }

    let rooted = workspace_root.join(default_relative);
    if rooted.exists() {
        return rooted;
    }
    rooted
}

/// Best-effort workspace root: the directory above `src-tauri/`.
pub(crate) fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(PathBuf::from)
        .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")))
}
